# Generated by Django 4.1.7 on 2023-05-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20)),
                ('core_value', models.CharField(max_length=100)),
                ('num_member', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ancient_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('statement', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.school')),
            ],
        ),
    ]
